### ISSUE TITLE
Latest version 1.0.9/1.0.10 gives an error function u is not a function

### ISSUE THREAD

**Issue by buhshanpjoshi** [formatjs/formatjs-old#60] opened 2019-06-04 17:25 UTC
### Which package?

intl-locales-supported

### Is this a BUG REPORT or FEATURE REQUEST? (choose one)

BUG

### Expected behavior

Should successfully be able to use the function of the libraray

### Current behavior

Page load fails with error 

### Step to reproduce for BUG REPORT

Uncaught TypeError: s is not a function
at Object.initializeIntlPolyfill (main.js:23)
at Object.start (main.js:38)

var areIntlLocalesSupported = require('intl-locales-supported');
if (global.Intl) {
// Determine if the built-in Intl has the locale data we need.
if (!areIntlLocalesSupported(localesMyAppSupports)) { //GIVES ERROR AT THIS LINE
var IntlPolyfill = require('intl');
Intl.NumberFormat = IntlPolyfill.NumberFormat;
Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat;
}
} else {
global.Intl = require('intl');
}

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls <package name>` | VERSION |
| `npm --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

| Browser | Version |
| --- | --- |
| NAME | VERSION |

**Comment by longlho** [comment] 2019-06-04 17:26
Do you have a stack trace?

**Comment by buhshanpjoshi** [comment] 2019-06-04 17:29
Uncaught TypeError: s is not a function
    at Object.initializeIntlPolyfill (main.js:23)
    at Object.start (main.js:38)

var areIntlLocalesSupported = require('intl-locales-supported');
if (global.Intl) {
      // Determine if the built-in `Intl` has the locale data we need.
      if (!**areIntlLocalesSupported**(localesMyAppSupports)) { //GIVES ERROR AT THIS LINE
        var IntlPolyfill = require('intl');
        Intl.NumberFormat   = IntlPolyfill.NumberFormat;
        Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat;
      }
    } else {
      global.Intl = require('intl');
    }

**Comment by longlho** [comment] 2019-06-04 18:01
Seems like your toolchain picks up the new ES6 import, the quick fix would be either to use `import areIntlLocalesSupported from 'intl-locales-supported'` or `var areIntlLocalesSupported = require('intl-locales-supported').default;`. Sorry for the breakage.

Duplicate of #56

**Comment by buhshanpjoshi** [comment] 2019-06-04 18:20
ok will try but for now i reverted back to 1.0.0 version which works for now

**Comment by longlho** [comment] 2019-06-05 23:22
closing as duplicate

**Closed as completed by longlho** 2019-06-05 23:22 UTC

**Comment by gfx** [comment] 2019-06-11 08:05
It is reproduced in the latest v1.0.10 with webpack, because the "module" section in package.json refers `lib/index.js` and it works differently from commonjs when it's loaded with `require()`.

My solution:

```typescript
import areIntlLocalsSupported from "intl-locales-supported";

if (globalThis.Intl) {
  const supportedLocales = ["en", "ja"];

  if (!areIntlLocalsSupported(supportedLocales)) {
    const IntlPolyfill = require("intl");
    Intl.NumberFormat = IntlPolyfill.NumberFormat;
    Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat;
  }
} else {
  globalThis.Intl = require("intl");
}

```

I think dropping the "module" section should solve this issue, or update doc to be the above.
