### ISSUE TITLE
[intl-messageformat-parser]: parse doesn't work in Firefox

### ISSUE THREAD

**Issue by ipanasenko** [formatjs/formatjs-old#153] opened 2019-08-12 16:32 UTC
**Which package?**
intl-messageformat-parse

**Describe the bug**
Packages fails in Firefox because of `/s` flag in regexp:
https://github.com/formatjs/formatjs/blob/master/packages/intl-messageformat-parser/src/printer.ts#L56

**To Reproduce**

Open Firefox with react-intl

**Expected behavior**
Should work, no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/576152/62881188-dff90280-bd37-11e9-8c4c-3e5553ba794a.png)

**Desktop (please complete the following information):**
Firefox 68.0.1

**Comment by longlho** [comment] 2019-08-12 17:03
this should be fixed in the latest release. We not longer expose `printer` in index file anymore

**Comment by longlho** [comment] 2019-08-12 19:08
duplicate of #147

**Closed as completed by longlho** 2019-08-12 19:08 UTC
Labels: bug
