### ISSUE TITLE
intl-utils/dist/invariant.d.ts(1,92): error TS1144: '{' or ';' expected

### ISSUE THREAD

**Issue by cahite** [formatjs/formatjs-old#435] opened 2020-01-07 16:35 UTC
**Which package?**
intl-messageformat

**Describe the bug**
ERROR: node_modules/@formatjs/intl-utils/dist/invariant.d.ts(1,92): error TS1144: '{' or ';' expected.
the problem comes in via a transitive dependency from the intl-messageformat package
`found "@formatjs/intl-utils@1.6.0"
info Reasons this module exists
   "intl-messageformat#intl-messageformat-parser#@formatjs#intl-unified-numberformat" depends on it     
   Hoisted from "intl-messageformat#intl-messageformat-parser#@formatjs#intl-unified-numberformat#@formatjs#intl-utils"`

Is it possible to fix the dependency on formatjs on the "old" one and to change the major version for the new dependency?

**To Reproduce**

1. install `intl-messageformat` package

**Expected behavior**
To install `intl-messageformat` package with no errors

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux
- Version 3.10.0-1062.el7.x86_64

**Additional context**
We started seeing this problem Jan 6, 2020

**Comment by longlho** [comment] 2020-01-07 17:05
We require TS@3.7+ in `@formatjs/intl-utils` v2 so you can either upgrade your TS, or pin down `intl-messageformat` to the previous version.

**Comment by longlho** [comment] 2020-01-07 17:06
closing as dupe of #410

**Closed as completed by longlho** 2020-01-07 17:06 UTC
Labels: bug

**Comment by cahite** [comment] 2020-01-07 21:15
I tried to pin down `intl-messageformat` to version 7.3.1 and I was still seeing the same error. Is it possible that `intl-messageformat` is still pulling the latest version of `intl-utils` instead of an older version that doesn't require TS3.7+?
